---
# tasks file for Nainterceptor.nodejs
- name: "Prepare - add node group"
  group:
    name: "{{ nodejs_group_name }}"
    system: yes
    state: present

- name: "Prepare - add node user"
  user:
    name: "{{ nodejs_user_name }}"
    group: "{{ nodejs_group_name }}"
    home: "{{ nodejs_home_path }}"
    createhome: yes
    shell: /bin/bash
    system: yes
    state: present

- name: "Install nvm"
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | sh
    creates={{ nodejs_home_path }}/.nvm/nvm.sh
  become: true
  become_user: "{{ nodejs_user_name }}"

- name: "Install nodeJS"
  shell: >
    /bin/bash -c "source {{ nodejs_home_path }}/.nvm/nvm.sh && nvm install {{ nodejs_version }} && nvm alias default {{ nodejs_version }}"
    creates={{ nodejs_home_path }}/.nvm/alias
  become: true
  become_user: "{{ nodejs_user_name }}"
